version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: breizhsport_app
    ports:
      - "8000:8000" # Port d'exposition pour accéder à l'application
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/breizhsportdb

  db:
    image: postgres:13
    container_name: breizhsport_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: breizhsportdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
