version: "3.8"

services:
  auth_service:
    build:
      context: ./auth_service/app
      dockerfile: Dockerfile
    ports:
      - "5001:5000" # Exemple de port
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb

  frontend_service:
    build:
      context: ./frontend_service/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/frontenddb

  product_service:
    build:
      context: ./product_service/app
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/productdb

  mongo:
    image: mongo
    ports:
      - "27017:27017"
