version: '3.9'

services:
  frontend_service:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - cesi_superviser_dev_app_network
    depends_on:
      - product_service
      - auth_service

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - cesi_superviser_dev_app_network
    volumes:
      - ./product_service/app:/app
    environment:
      MONGO_HOST: mongo-product
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_DB: products
    depends_on:
      - mongo-product

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - cesi_superviser_dev_app_network
    volumes:
      - ./auth_service/app:/app
    environment:
      MONGO_HOST: mongo-auth
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_DB: auth
    depends_on:
      - mongo-auth

  mongo-product:
    image: mongo:6.0
    container_name: mongo-product
    ports:
      - "27018:27017"
    networks:
      - cesi_superviser_dev_app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init/fixtures:/fixtures
      - ./mongo-init/import_products.sh:/docker-entrypoint-initdb.d/mongo_import.sh

  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    ports:
      - "27017:27017"
    networks:
      - cesi_superviser_dev_app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init/fixtures:/fixtures
      - ./mongo-init/import_users.sh:/docker-entrypoint-initdb.d/mongo_import.sh

networks:
  cesi_superviser_dev_app_network:
    driver: bridge
