version: "3"

services:
  app:
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/breizhsportdb
    depends_on:
      - mongo

  test:
    build: .
    command: python -m unittest discover -s test
    environment:
      MONGO_URI: mongodb://mongo:27017/breizhsportdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({ ping: 1 })' | mongo breizhsportdb --quiet",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
