services:
  # Base de données pour le service d'authentification
  mongo-auth:
    image: mongo:6.0
    container_name: mongo-auth
    environment:
      MONGO_INITDB_DATABASE: authdb
    volumes:
      - auth_data:/data/db
    networks:
      - backend

  # Service d'authentification
  auth_service:
    build:
      context: ./auth_service
      dockerfile: app/Dockerfile
    container_name: auth_service
    environment:
      MONGO_URI: mongodb://mongo-auth:27017/authdb
    depends_on:
      - mongo-auth
    volumes:
      - ./auth_service/app:/app
    ports:
      - "8001:8001"
    networks:
      - backend

  # Base de données pour le service de produits
  mongo-product:
    image: mongo:6.0
    container_name: mongo-product
    environment:
      MONGO_INITDB_DATABASE: productdb
    volumes:
      - product_data:/data/db
    networks:
      - backend

  # Service de gestion des produits
  product_service:
    build:
      context: ./product_service
      dockerfile: app/Dockerfile
    container_name: product_service
    environment:
      MONGO_URI: mongodb://mongo-product:27017/productdb
    depends_on:
      - mongo-product
    volumes:
      - ./product_service/app:/app
    ports:
      - "8002:8002"
    networks:
      - backend

  # Service frontend
  frontend_service:
    build:
      context: ./frontend_service
      dockerfile: app/Dockerfile
    container_name: frontend_service
    volumes:
      - ./frontend_service/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - product_service
    networks:
      - backend

volumes:
  auth_data:
  product_data:

networks:
  backend:
    driver: bridge
