services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  auth_service:
    build:
      context: ./auth_service/app
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    networks:
      - backend

  product_service:
    build:
      context: ./product_service/app
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    networks:
      - backend

  frontend_service:
    build:
      context: ./frontend_service/app
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - product_service
    networks:
      - backend

networks:
  backend:
    driver: bridge
