version: "3"

services:
  app:
    build: .
    command: python /app/main.py  # Assurez-vous d'utiliser le chemin absolu vers main.py
    volumes:
      - .:/app  # Monte le répertoire actuel sur /app dans le conteneur
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017/breizhsportdb
    depends_on:
      - mongo

  test:
    build: .
    command: python -m unittest discover -s /app/tests  # Assurez-vous que les tests sont dans /app/tests
    volumes:
      - .:/app  # Monte le répertoire actuel sur /app dans le conteneur
    environment:
      MONGO_URI: mongodb://mongo:27017/breizhsportdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          "'db.runCommand({ ping: 1 })' | mongo breizhsportdb --quiet",
        ]
      interval: 11s
      timeout: 5s
      retries: 5
