sonar.projectKey=BastienLopez_CESI_Superviser_dev_app
sonar.organization=bastienlopez
sonar.host.url=https://sonarcloud.io

# Désactiver les Quality Gates pour éviter les échecs bloquants dans CI/CD
sonar.qualitygate.wait=false

# Exclure tous les fichiers pour la couverture (si intentionnel)
sonar.coverage.exclusions=**/*

# Exclure les duplications de code
sonar.cpd.exclusions=**/*
