apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongo-product
  name: mongo-product
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-product
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mongo-product
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:6.0
          name: mongo-product
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /fixtures
              name: mongo-product-claim0
            - mountPath: /docker-entrypoint-initdb.d/mongo_import.sh
              name: mongo-product-claim1
      restartPolicy: Always
      volumes:
        - name: mongo-product-claim0
          persistentVolumeClaim:
            claimName: mongo-product-claim0
        - name: mongo-product-claim1
          persistentVolumeClaim:
            claimName: mongo-product-claim1
