apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: auth-service-claim0
  name: auth-service-claim0
  namespace: auth-service-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
