apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoiRGFtaWVuLUQiLCJwYXNzd29yZCI6ImdscGF0LWtzQXJCb2JRc1BFQUU4WG5zOVBiIiwiZW1haWwiOiJkZXZvdGkuZGFtaWVuQGdtYWlsLmNvbSIsImF1dGgiOiJSR0Z0YVdWdUxVUTZaMnh3WVhRdGEzTkJja0p2WWxGelVFVkJSVGhZYm5NNVVHST0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: auth-service-namespace
type: kubernetes.io/dockerconfigjson