apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
  namespace: frontend-service-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: frontend-service
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
        - image: registry.gitlab.com/damien-d/breizhsport/frontend_service:latest
          name: frontend-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
