name: Docker Test Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Run tests
        run: docker compose up --build --abort-on-container-exit

      - name: Clean up
        if: always()
        run: docker compose down
