name: Docker Test Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Mettre à jour et installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # 3. Construire et exécuter les conteneurs avec Docker Compose
      - name: Build and Run tests with Docker Compose
        run: docker compose up --build --abort-on-container-exit

      # 4. Nettoyer les conteneurs après les tests
      - name: Clean up
        if: always()
        run: docker compose down
