name: Docker Test Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: '2.x'  # Installe Docker Compose v2, si nécessaire

      - name: Build Docker services
        run: docker compose up -d --build  # Remplacer "docker-compose" par "docker compose"

      # Lancer les tests pour chaque service
      - name: Run tests for auth_service
        run: docker compose run --rm auth_service python -m pytest test.py  # Remplacer "docker-compose" par "docker compose"

      - name: Run tests for product_service
        run: docker compose run --rm product_service python -m pytest test_product_service.py  # Remplacer "docker-compose" par "docker compose"

      - name: Run tests for frontend_service
        run: docker compose run --rm frontend_service pytest  # Remplacer "docker-compose" par "docker compose"

      - name: Clean up Docker
        if: always()
        run: docker compose down  # Remplacer "docker-compose" par "docker compose"
