name: Docker Test Workflow

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Docker Compose avec pip
      - name: Install Docker Compose with pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install docker-compose

      # 3. Set up Docker Buildx (optionnel mais utile pour la compatibilité)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Construire et exécuter les conteneurs avec Docker Compose
      - name: Build and Run tests with Docker Compose
        run: docker-compose up --build --abort-on-container-exit

      # 5. Nettoyer les conteneurs après les tests
      - name: Clean up
        if: always()
        run: docker-compose down
